'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


'
'This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
'
Namespace WS_SEGURIDAD
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tempuri.org/WS_SEGURIDAD/Service1", ConfigurationName:="WS_SEGURIDAD.WS_SeguridadSoap")>  _
    Public Interface WS_SeguridadSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SEGURIDAD/Service1/EncriptarPassword", ReplyAction:="*")>  _
        Function EncriptarPasswordAsync(ByVal request As WS_SEGURIDAD.EncriptarPasswordRequest) As System.Threading.Tasks.Task(Of WS_SEGURIDAD.EncriptarPasswordResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SEGURIDAD/Service1/DesencriptarPassword", ReplyAction:="*")>  _
        Function DesencriptarPasswordAsync(ByVal request As WS_SEGURIDAD.DesencriptarPasswordRequest) As System.Threading.Tasks.Task(Of WS_SEGURIDAD.DesencriptarPasswordResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EncriptarPasswordRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EncriptarPassword", [Namespace]:="http://tempuri.org/WS_SEGURIDAD/Service1", Order:=0)>  _
        Public Body As WS_SEGURIDAD.EncriptarPasswordRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_SEGURIDAD.EncriptarPasswordRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/WS_SEGURIDAD/Service1")>  _
    Partial Public Class EncriptarPasswordRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public sPassword As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sPassword As String)
            MyBase.New
            Me.sPassword = sPassword
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EncriptarPasswordResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EncriptarPasswordResponse", [Namespace]:="http://tempuri.org/WS_SEGURIDAD/Service1", Order:=0)>  _
        Public Body As WS_SEGURIDAD.EncriptarPasswordResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_SEGURIDAD.EncriptarPasswordResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/WS_SEGURIDAD/Service1")>  _
    Partial Public Class EncriptarPasswordResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public EncriptarPasswordResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EncriptarPasswordResult As String)
            MyBase.New
            Me.EncriptarPasswordResult = EncriptarPasswordResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DesencriptarPasswordRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DesencriptarPassword", [Namespace]:="http://tempuri.org/WS_SEGURIDAD/Service1", Order:=0)>  _
        Public Body As WS_SEGURIDAD.DesencriptarPasswordRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_SEGURIDAD.DesencriptarPasswordRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/WS_SEGURIDAD/Service1")>  _
    Partial Public Class DesencriptarPasswordRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public sPasswordEncriptada As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sPasswordEncriptada As String)
            MyBase.New
            Me.sPasswordEncriptada = sPasswordEncriptada
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DesencriptarPasswordResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DesencriptarPasswordResponse", [Namespace]:="http://tempuri.org/WS_SEGURIDAD/Service1", Order:=0)>  _
        Public Body As WS_SEGURIDAD.DesencriptarPasswordResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_SEGURIDAD.DesencriptarPasswordResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/WS_SEGURIDAD/Service1")>  _
    Partial Public Class DesencriptarPasswordResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DesencriptarPasswordResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DesencriptarPasswordResult As String)
            MyBase.New
            Me.DesencriptarPasswordResult = DesencriptarPasswordResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WS_SeguridadSoapChannel
        Inherits WS_SEGURIDAD.WS_SeguridadSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WS_SeguridadSoapClient
        Inherits System.ServiceModel.ClientBase(Of WS_SEGURIDAD.WS_SeguridadSoap)
        Implements WS_SEGURIDAD.WS_SeguridadSoap
        
        ''' <summary>
        ''' Implement this partial method to configure the service endpoint.
        ''' </summary>
        ''' <param name="serviceEndpoint">The endpoint to configure</param>
        ''' <param name="clientCredentials">The client credentials</param>
        Partial Private Shared Sub ConfigureEndpoint(ByVal serviceEndpoint As System.ServiceModel.Description.ServiceEndpoint, ByVal clientCredentials As System.ServiceModel.Description.ClientCredentials)
        End Sub
        
        Public Sub New()
            MyBase.New(WS_SeguridadSoapClient.GetDefaultBinding, WS_SeguridadSoapClient.GetDefaultEndpointAddress)
            Me.Endpoint.Name = EndpointConfiguration.WS_SeguridadSoap.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration)
            MyBase.New(WS_SeguridadSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_SeguridadSoapClient.GetEndpointAddress(endpointConfiguration))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As String)
            MyBase.New(WS_SeguridadSoapClient.GetBindingForEndpoint(endpointConfiguration), New System.ServiceModel.EndpointAddress(remoteAddress))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(WS_SeguridadSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_SEGURIDAD_WS_SeguridadSoap_EncriptarPasswordAsync(ByVal request As WS_SEGURIDAD.EncriptarPasswordRequest) As System.Threading.Tasks.Task(Of WS_SEGURIDAD.EncriptarPasswordResponse) Implements WS_SEGURIDAD.WS_SeguridadSoap.EncriptarPasswordAsync
            Return MyBase.Channel.EncriptarPasswordAsync(request)
        End Function
        
        Public Function EncriptarPasswordAsync(ByVal sPassword As String) As System.Threading.Tasks.Task(Of WS_SEGURIDAD.EncriptarPasswordResponse)
            Dim inValue As WS_SEGURIDAD.EncriptarPasswordRequest = New WS_SEGURIDAD.EncriptarPasswordRequest()
            inValue.Body = New WS_SEGURIDAD.EncriptarPasswordRequestBody()
            inValue.Body.sPassword = sPassword
            Return CType(Me,WS_SEGURIDAD.WS_SeguridadSoap).EncriptarPasswordAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_SEGURIDAD_WS_SeguridadSoap_DesencriptarPasswordAsync(ByVal request As WS_SEGURIDAD.DesencriptarPasswordRequest) As System.Threading.Tasks.Task(Of WS_SEGURIDAD.DesencriptarPasswordResponse) Implements WS_SEGURIDAD.WS_SeguridadSoap.DesencriptarPasswordAsync
            Return MyBase.Channel.DesencriptarPasswordAsync(request)
        End Function
        
        Public Function DesencriptarPasswordAsync(ByVal sPasswordEncriptada As String) As System.Threading.Tasks.Task(Of WS_SEGURIDAD.DesencriptarPasswordResponse)
            Dim inValue As WS_SEGURIDAD.DesencriptarPasswordRequest = New WS_SEGURIDAD.DesencriptarPasswordRequest()
            inValue.Body = New WS_SEGURIDAD.DesencriptarPasswordRequestBody()
            inValue.Body.sPasswordEncriptada = sPasswordEncriptada
            Return CType(Me,WS_SEGURIDAD.WS_SeguridadSoap).DesencriptarPasswordAsync(inValue)
        End Function
        
        Public Overridable Function OpenAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndOpen)
        End Function
        
        Public Overridable Function CloseAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndClose)
        End Function
        
        Private Shared Function GetBindingForEndpoint(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.Channels.Binding
            If (endpointConfiguration = EndpointConfiguration.WS_SeguridadSoap) Then
                Dim result As System.ServiceModel.BasicHttpBinding = New System.ServiceModel.BasicHttpBinding()
                result.MaxBufferSize = Integer.MaxValue
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max
                result.MaxReceivedMessageSize = Integer.MaxValue
                result.AllowCookies = true
                Return result
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetEndpointAddress(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.EndpointAddress
            If (endpointConfiguration = EndpointConfiguration.WS_SeguridadSoap) Then
                Return New System.ServiceModel.EndpointAddress("http://213.0.25.236:94/WS_Seguridad/WS_Seguridad.asmx")
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetDefaultBinding() As System.ServiceModel.Channels.Binding
            Return WS_SeguridadSoapClient.GetBindingForEndpoint(EndpointConfiguration.WS_SeguridadSoap)
        End Function
        
        Private Shared Function GetDefaultEndpointAddress() As System.ServiceModel.EndpointAddress
            Return WS_SeguridadSoapClient.GetEndpointAddress(EndpointConfiguration.WS_SeguridadSoap)
        End Function
        
        Public Enum EndpointConfiguration
            
            WS_SeguridadSoap
        End Enum
    End Class
End Namespace
