'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


'
'This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
'
Namespace WS_SPFM
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", ConfigurationName:="WS_SPFM.WS_SPFMSoap")>  _
    Public Interface WS_SPFMSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/existeEnTCOMPROVE", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function existeEnTCOMPROVEAsync(ByVal iCodigoProveedor As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/existeEnTEMPLEADO", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function existeEnTEMPLEADOAsync(ByVal iCodigoPersona As Integer) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/existeNumeroDocumento", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function existeNumeroDocumentoAsync(ByVal sNumDocumento As String) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/insertarEusuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertarEusuarioAsync( _
                    ByVal sNomPersona As String,  _
                    ByVal sCodPersona As String,  _
                    ByVal sDesEMail As String,  _
                    ByVal sDesDomicilio As String,  _
                    ByVal iCodPoblacion As Integer,  _
                    ByVal iCodPostal As Integer,  _
                    ByVal iCodProvincia As Integer,  _
                    ByVal sNumTelefono As String,  _
                    ByVal sNumDocumento As String,  _
                    ByVal iCodTipoDocumento As Short,  _
                    ByVal sFecNacimiento As String,  _
                    ByVal iNumColegiado As Integer,  _
                    ByVal sNumFax As String,  _
                    ByVal cIndCertificado As Char,  _
                    ByVal sObservacion As String,  _
                    ByVal sComercial As String,  _
                    ByVal sFecAlta As String) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/insertarEusuemp", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertarEusuempAsync(ByVal iCodUsuario As Integer, ByVal sNumCif As String, ByVal CodProvincia As Integer, ByVal iTipoUsuario As Integer, ByVal sNumCcc As String, ByVal iNumReg As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/insertarEusucolab", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertarEusucolabAsync(ByVal iCodUsuario As Integer, ByVal iCodColaborador As Integer) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/insertarEusuca", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertarEusucaAsync(ByVal iCodUsuario As Integer, ByVal iCodigoCentroAsistencial As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/insertarEususumin", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertarEususuminAsync(ByVal iCodUsuario As Integer, ByVal iProveedor As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        'CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/insertarTipoUsuario", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertarTipoUsuarioAsync(ByVal request As WS_SPFM.insertarTipoUsuarioRequest) As System.Threading.Tasks.Task(Of WS_SPFM.insertarTipoUsuarioResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/insertarEusupwd", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function insertarEusupwdAsync(ByVal iCodUsuario As Integer, ByVal sDesPwd As String) As System.Threading.Tasks.Task(Of Object)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/obtenerResponsablesAsesoria", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function obtenerResponsablesAsesoriaAsync(ByVal iPermisoAsesoriaInformatica As Integer) As System.Threading.Tasks.Task(Of WS_SPFM.ArrayOfXElement)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/ObtenerCorreo", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtenerCorreoAsync(ByVal iCodPersona As Integer) As System.Threading.Tasks.Task(Of String)
        
        'CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/dameDatosPeticion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function dameDatosPeticionAsync(ByVal request As WS_SPFM.dameDatosPeticionRequest) As System.Threading.Tasks.Task(Of WS_SPFM.dameDatosPeticionResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/dameDescripcionTipoVia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function dameDescripcionTipoViaAsync(ByVal sCodTipoVia As String) As System.Threading.Tasks.Task(Of String)
        
        'CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/damePoblacionProvincia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function damePoblacionProvinciaAsync(ByVal request As WS_SPFM.damePoblacionProvinciaRequest) As System.Threading.Tasks.Task(Of WS_SPFM.damePoblacionProvinciaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/dameDirectorProvincial", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function dameDirectorProvincialAsync(ByVal iCodPoblacion As Integer, ByVal iCodPersona As Integer, ByVal sNombreDirector As String) As System.Threading.Tasks.Task
        
        'CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/dameDirectorGeneralProvincia", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function dameDirectorGeneralProvinciaAsync(ByVal request As WS_SPFM.dameDirectorGeneralProvinciaRequest) As System.Threading.Tasks.Task(Of WS_SPFM.dameDirectorGeneralProvinciaResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/ActualizarDirectorProvincial", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ActualizarDirectorProvincialAsync(ByVal iCodPersona As Integer, ByVal iCodUsuario As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/avisoFM", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function avisoFMAsync(ByVal iCodPersonaResponsable As Integer, ByVal sNombrePersona As String, ByVal iTipoAviso As Integer, ByVal iGrupo As Integer) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/WS_SPFM/Service1/avisoSPFM", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function avisoSPFMAsync(ByVal iCodPersonaResponsable As Integer, ByVal sNombrePersona As String, ByVal iTipoAviso As Integer, ByVal iGrupo As Integer) As System.Threading.Tasks.Task
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="insertarTipoUsuario", WrapperNamespace:="http://tempuri.org/WS_SPFM/Service1", IsWrapped:=true)>  _
    Partial Public Class insertarTipoUsuarioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=0)>  _
        Public iTipoUsuario As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=1)>  _
        Public iCodUsuario As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=2)>  _
        Public sFecAlta As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=3)>  _
        Public iModificado As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal iTipoUsuario As Integer, ByVal iCodUsuario As Integer, ByVal sFecAlta As String, ByVal iModificado As Integer)
            MyBase.New
            Me.iTipoUsuario = iTipoUsuario
            Me.iCodUsuario = iCodUsuario
            Me.sFecAlta = sFecAlta
            Me.iModificado = iModificado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="insertarTipoUsuarioResponse", WrapperNamespace:="http://tempuri.org/WS_SPFM/Service1", IsWrapped:=true)>  _
    Partial Public Class insertarTipoUsuarioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=0)>  _
        Public iModificado As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal iModificado As Integer)
            MyBase.New
            Me.iModificado = iModificado
        End Sub
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.w3.org/2001/XMLSchema")>  _
    Partial Public Class schema
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="dameDatosPeticion", WrapperNamespace:="http://tempuri.org/WS_SPFM/Service1", IsWrapped:=true)>  _
    Partial Public Class dameDatosPeticionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=0)>  _
        Public iCodUsuario As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=1)>  _
        Public sDireccion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=2)>  _
        Public iCodPoblacion As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=3)>  _
        Public sDesTipoUsuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=4)>  _
        Public sNombrePersona As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=5)>  _
        Public sTipoIdentif As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=6)>  _
        Public sNumDocumento As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=7)>  _
        Public sFecNacimiento As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=8)>  _
        Public sNumColegiado As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=9)>  _
        Public sCodProveedor As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=10)>  _
        Public sCodCentroAsistencial As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=11)>  _
        Public sNumCif As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=12)>  _
        Public sCodigoPostal As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=13)>  _
        Public sNumTelefono As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=14)>  _
        Public sNumFax As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=15)>  _
        Public sDesEMail As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=16)>  _
        Public cIndCertificado As Char
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=17)>  _
        Public sDesEstado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal iCodUsuario As Integer,  _
                    ByVal sDireccion As String,  _
                    ByVal iCodPoblacion As Integer,  _
                    ByVal sDesTipoUsuario As String,  _
                    ByVal sNombrePersona As String,  _
                    ByVal sTipoIdentif As String,  _
                    ByVal sNumDocumento As String,  _
                    ByVal sFecNacimiento As String,  _
                    ByVal sNumColegiado As String,  _
                    ByVal sCodProveedor As String,  _
                    ByVal sCodCentroAsistencial As String,  _
                    ByVal sNumCif As String,  _
                    ByVal sCodigoPostal As String,  _
                    ByVal sNumTelefono As String,  _
                    ByVal sNumFax As String,  _
                    ByVal sDesEMail As String,  _
                    ByVal cIndCertificado As Char,  _
                    ByVal sDesEstado As String)
            MyBase.New
            Me.iCodUsuario = iCodUsuario
            Me.sDireccion = sDireccion
            Me.iCodPoblacion = iCodPoblacion
            Me.sDesTipoUsuario = sDesTipoUsuario
            Me.sNombrePersona = sNombrePersona
            Me.sTipoIdentif = sTipoIdentif
            Me.sNumDocumento = sNumDocumento
            Me.sFecNacimiento = sFecNacimiento
            Me.sNumColegiado = sNumColegiado
            Me.sCodProveedor = sCodProveedor
            Me.sCodCentroAsistencial = sCodCentroAsistencial
            Me.sNumCif = sNumCif
            Me.sCodigoPostal = sCodigoPostal
            Me.sNumTelefono = sNumTelefono
            Me.sNumFax = sNumFax
            Me.sDesEMail = sDesEMail
            Me.cIndCertificado = cIndCertificado
            Me.sDesEstado = sDesEstado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="dameDatosPeticionResponse", WrapperNamespace:="http://tempuri.org/WS_SPFM/Service1", IsWrapped:=true)>  _
    Partial Public Class dameDatosPeticionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=0)>  _
        Public sDireccion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=1)>  _
        Public iCodPoblacion As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=2)>  _
        Public sDesTipoUsuario As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=3)>  _
        Public sNombrePersona As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=4)>  _
        Public sTipoIdentif As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=5)>  _
        Public sNumDocumento As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=6)>  _
        Public sFecNacimiento As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=7)>  _
        Public sNumColegiado As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=8)>  _
        Public sCodProveedor As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=9)>  _
        Public sCodCentroAsistencial As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=10)>  _
        Public sNumCif As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=11)>  _
        Public sCodigoPostal As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=12)>  _
        Public sNumTelefono As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=13)>  _
        Public sNumFax As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=14)>  _
        Public sDesEMail As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=15)>  _
        Public cIndCertificado As Char
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=16)>  _
        Public sDesEstado As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New( _
                    ByVal sDireccion As String,  _
                    ByVal iCodPoblacion As Integer,  _
                    ByVal sDesTipoUsuario As String,  _
                    ByVal sNombrePersona As String,  _
                    ByVal sTipoIdentif As String,  _
                    ByVal sNumDocumento As String,  _
                    ByVal sFecNacimiento As String,  _
                    ByVal sNumColegiado As String,  _
                    ByVal sCodProveedor As String,  _
                    ByVal sCodCentroAsistencial As String,  _
                    ByVal sNumCif As String,  _
                    ByVal sCodigoPostal As String,  _
                    ByVal sNumTelefono As String,  _
                    ByVal sNumFax As String,  _
                    ByVal sDesEMail As String,  _
                    ByVal cIndCertificado As Char,  _
                    ByVal sDesEstado As String)
            MyBase.New
            Me.sDireccion = sDireccion
            Me.iCodPoblacion = iCodPoblacion
            Me.sDesTipoUsuario = sDesTipoUsuario
            Me.sNombrePersona = sNombrePersona
            Me.sTipoIdentif = sTipoIdentif
            Me.sNumDocumento = sNumDocumento
            Me.sFecNacimiento = sFecNacimiento
            Me.sNumColegiado = sNumColegiado
            Me.sCodProveedor = sCodProveedor
            Me.sCodCentroAsistencial = sCodCentroAsistencial
            Me.sNumCif = sNumCif
            Me.sCodigoPostal = sCodigoPostal
            Me.sNumTelefono = sNumTelefono
            Me.sNumFax = sNumFax
            Me.sDesEMail = sDesEMail
            Me.cIndCertificado = cIndCertificado
            Me.sDesEstado = sDesEstado
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="damePoblacionProvincia", WrapperNamespace:="http://tempuri.org/WS_SPFM/Service1", IsWrapped:=true)>  _
    Partial Public Class damePoblacionProvinciaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=0)>  _
        Public iCodPoblacion As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=1)>  _
        Public sDesPoblacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=2)>  _
        Public sDesProvincia As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal iCodPoblacion As Integer, ByVal sDesPoblacion As String, ByVal sDesProvincia As String)
            MyBase.New
            Me.iCodPoblacion = iCodPoblacion
            Me.sDesPoblacion = sDesPoblacion
            Me.sDesProvincia = sDesProvincia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="damePoblacionProvinciaResponse", WrapperNamespace:="http://tempuri.org/WS_SPFM/Service1", IsWrapped:=true)>  _
    Partial Public Class damePoblacionProvinciaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=0)>  _
        Public sDesPoblacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=1)>  _
        Public sDesProvincia As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal sDesPoblacion As String, ByVal sDesProvincia As String)
            MyBase.New
            Me.sDesPoblacion = sDesPoblacion
            Me.sDesProvincia = sDesProvincia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="dameDirectorGeneralProvincia", WrapperNamespace:="http://tempuri.org/WS_SPFM/Service1", IsWrapped:=true)>  _
    Partial Public Class dameDirectorGeneralProvinciaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=0)>  _
        Public iCodProvincia As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=1)>  _
        Public iCodPersona As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=2)>  _
        Public sNombreDirector As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal iCodProvincia As Integer, ByVal iCodPersona As Integer, ByVal sNombreDirector As String)
            MyBase.New
            Me.iCodProvincia = iCodProvincia
            Me.iCodPersona = iCodPersona
            Me.sNombreDirector = sNombreDirector
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="dameDirectorGeneralProvinciaResponse", WrapperNamespace:="http://tempuri.org/WS_SPFM/Service1", IsWrapped:=true)>  _
    Partial Public Class dameDirectorGeneralProvinciaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=0)>  _
        Public iCodPersona As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/WS_SPFM/Service1", Order:=1)>  _
        Public sNombreDirector As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal iCodPersona As Integer, ByVal sNombreDirector As String)
            MyBase.New
            Me.iCodPersona = iCodPersona
            Me.sNombreDirector = sNombreDirector
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WS_SPFMSoapChannel
        Inherits WS_SPFM.WS_SPFMSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WS_SPFMSoapClient
        Inherits System.ServiceModel.ClientBase(Of WS_SPFM.WS_SPFMSoap)
        Implements WS_SPFM.WS_SPFMSoap
        
        ''' <summary>
        ''' Implement this partial method to configure the service endpoint.
        ''' </summary>
        ''' <param name="serviceEndpoint">The endpoint to configure</param>
        ''' <param name="clientCredentials">The client credentials</param>
        Partial Private Shared Sub ConfigureEndpoint(ByVal serviceEndpoint As System.ServiceModel.Description.ServiceEndpoint, ByVal clientCredentials As System.ServiceModel.Description.ClientCredentials)
        End Sub
        
        Public Sub New()
            MyBase.New(WS_SPFMSoapClient.GetDefaultBinding, WS_SPFMSoapClient.GetDefaultEndpointAddress)
            Me.Endpoint.Name = EndpointConfiguration.WS_SPFMSoap.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration)
            MyBase.New(WS_SPFMSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_SPFMSoapClient.GetEndpointAddress(endpointConfiguration))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As String)
            MyBase.New(WS_SPFMSoapClient.GetBindingForEndpoint(endpointConfiguration), New System.ServiceModel.EndpointAddress(remoteAddress))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(WS_SPFMSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function existeEnTCOMPROVEAsync(ByVal iCodigoProveedor As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements WS_SPFM.WS_SPFMSoap.existeEnTCOMPROVEAsync
            Return MyBase.Channel.existeEnTCOMPROVEAsync(iCodigoProveedor)
        End Function
        
        Public Function existeEnTEMPLEADOAsync(ByVal iCodigoPersona As Integer) As System.Threading.Tasks.Task(Of Boolean) Implements WS_SPFM.WS_SPFMSoap.existeEnTEMPLEADOAsync
            Return MyBase.Channel.existeEnTEMPLEADOAsync(iCodigoPersona)
        End Function
        
        Public Function existeNumeroDocumentoAsync(ByVal sNumDocumento As String) As System.Threading.Tasks.Task(Of Boolean) Implements WS_SPFM.WS_SPFMSoap.existeNumeroDocumentoAsync
            Return MyBase.Channel.existeNumeroDocumentoAsync(sNumDocumento)
        End Function
        
        Public Function insertarEusuarioAsync( _
                    ByVal sNomPersona As String,  _
                    ByVal sCodPersona As String,  _
                    ByVal sDesEMail As String,  _
                    ByVal sDesDomicilio As String,  _
                    ByVal iCodPoblacion As Integer,  _
                    ByVal iCodPostal As Integer,  _
                    ByVal iCodProvincia As Integer,  _
                    ByVal sNumTelefono As String,  _
                    ByVal sNumDocumento As String,  _
                    ByVal iCodTipoDocumento As Short,  _
                    ByVal sFecNacimiento As String,  _
                    ByVal iNumColegiado As Integer,  _
                    ByVal sNumFax As String,  _
                    ByVal cIndCertificado As Char,  _
                    ByVal sObservacion As String,  _
                    ByVal sComercial As String,  _
                    ByVal sFecAlta As String) As System.Threading.Tasks.Task(Of Integer) Implements WS_SPFM.WS_SPFMSoap.insertarEusuarioAsync
            Return MyBase.Channel.insertarEusuarioAsync(sNomPersona, sCodPersona, sDesEMail, sDesDomicilio, iCodPoblacion, iCodPostal, iCodProvincia, sNumTelefono, sNumDocumento, iCodTipoDocumento, sFecNacimiento, iNumColegiado, sNumFax, cIndCertificado, sObservacion, sComercial, sFecAlta)
        End Function
        
        Public Function insertarEusuempAsync(ByVal iCodUsuario As Integer, ByVal sNumCif As String, ByVal CodProvincia As Integer, ByVal iTipoUsuario As Integer, ByVal sNumCcc As String, ByVal iNumReg As Integer) As System.Threading.Tasks.Task(Of Integer) Implements WS_SPFM.WS_SPFMSoap.insertarEusuempAsync
            Return MyBase.Channel.insertarEusuempAsync(iCodUsuario, sNumCif, CodProvincia, iTipoUsuario, sNumCcc, iNumReg)
        End Function
        
        Public Function insertarEusucolabAsync(ByVal iCodUsuario As Integer, ByVal iCodColaborador As Integer) As System.Threading.Tasks.Task(Of Object) Implements WS_SPFM.WS_SPFMSoap.insertarEusucolabAsync
            Return MyBase.Channel.insertarEusucolabAsync(iCodUsuario, iCodColaborador)
        End Function
        
        Public Function insertarEusucaAsync(ByVal iCodUsuario As Integer, ByVal iCodigoCentroAsistencial As Integer) As System.Threading.Tasks.Task(Of Integer) Implements WS_SPFM.WS_SPFMSoap.insertarEusucaAsync
            Return MyBase.Channel.insertarEusucaAsync(iCodUsuario, iCodigoCentroAsistencial)
        End Function
        
        Public Function insertarEususuminAsync(ByVal iCodUsuario As Integer, ByVal iProveedor As Integer) As System.Threading.Tasks.Task(Of Integer) Implements WS_SPFM.WS_SPFMSoap.insertarEususuminAsync
            Return MyBase.Channel.insertarEususuminAsync(iCodUsuario, iProveedor)
        End Function
        
        Public Function insertarTipoUsuarioAsync(ByVal request As WS_SPFM.insertarTipoUsuarioRequest) As System.Threading.Tasks.Task(Of WS_SPFM.insertarTipoUsuarioResponse) Implements WS_SPFM.WS_SPFMSoap.insertarTipoUsuarioAsync
            Return MyBase.Channel.insertarTipoUsuarioAsync(request)
        End Function
        
        Public Function insertarEusupwdAsync(ByVal iCodUsuario As Integer, ByVal sDesPwd As String) As System.Threading.Tasks.Task(Of Object) Implements WS_SPFM.WS_SPFMSoap.insertarEusupwdAsync
            Return MyBase.Channel.insertarEusupwdAsync(iCodUsuario, sDesPwd)
        End Function
        
        Public Function obtenerResponsablesAsesoriaAsync(ByVal iPermisoAsesoriaInformatica As Integer) As System.Threading.Tasks.Task(Of WS_SPFM.ArrayOfXElement) Implements WS_SPFM.WS_SPFMSoap.obtenerResponsablesAsesoriaAsync
            Return MyBase.Channel.obtenerResponsablesAsesoriaAsync(iPermisoAsesoriaInformatica)
        End Function
        
        Public Function ObtenerCorreoAsync(ByVal iCodPersona As Integer) As System.Threading.Tasks.Task(Of String) Implements WS_SPFM.WS_SPFMSoap.ObtenerCorreoAsync
            Return MyBase.Channel.ObtenerCorreoAsync(iCodPersona)
        End Function
        
        Public Function dameDatosPeticionAsync(ByVal request As WS_SPFM.dameDatosPeticionRequest) As System.Threading.Tasks.Task(Of WS_SPFM.dameDatosPeticionResponse) Implements WS_SPFM.WS_SPFMSoap.dameDatosPeticionAsync
            Return MyBase.Channel.dameDatosPeticionAsync(request)
        End Function
        
        Public Function dameDescripcionTipoViaAsync(ByVal sCodTipoVia As String) As System.Threading.Tasks.Task(Of String) Implements WS_SPFM.WS_SPFMSoap.dameDescripcionTipoViaAsync
            Return MyBase.Channel.dameDescripcionTipoViaAsync(sCodTipoVia)
        End Function
        
        Public Function damePoblacionProvinciaAsync(ByVal request As WS_SPFM.damePoblacionProvinciaRequest) As System.Threading.Tasks.Task(Of WS_SPFM.damePoblacionProvinciaResponse) Implements WS_SPFM.WS_SPFMSoap.damePoblacionProvinciaAsync
            Return MyBase.Channel.damePoblacionProvinciaAsync(request)
        End Function
        
        Public Function dameDirectorProvincialAsync(ByVal iCodPoblacion As Integer, ByVal iCodPersona As Integer, ByVal sNombreDirector As String) As System.Threading.Tasks.Task Implements WS_SPFM.WS_SPFMSoap.dameDirectorProvincialAsync
            Return MyBase.Channel.dameDirectorProvincialAsync(iCodPoblacion, iCodPersona, sNombreDirector)
        End Function
        
        Public Function dameDirectorGeneralProvinciaAsync(ByVal request As WS_SPFM.dameDirectorGeneralProvinciaRequest) As System.Threading.Tasks.Task(Of WS_SPFM.dameDirectorGeneralProvinciaResponse) Implements WS_SPFM.WS_SPFMSoap.dameDirectorGeneralProvinciaAsync
            Return MyBase.Channel.dameDirectorGeneralProvinciaAsync(request)
        End Function
        
        Public Function ActualizarDirectorProvincialAsync(ByVal iCodPersona As Integer, ByVal iCodUsuario As Integer) As System.Threading.Tasks.Task(Of Integer) Implements WS_SPFM.WS_SPFMSoap.ActualizarDirectorProvincialAsync
            Return MyBase.Channel.ActualizarDirectorProvincialAsync(iCodPersona, iCodUsuario)
        End Function
        
        Public Function avisoFMAsync(ByVal iCodPersonaResponsable As Integer, ByVal sNombrePersona As String, ByVal iTipoAviso As Integer, ByVal iGrupo As Integer) As System.Threading.Tasks.Task Implements WS_SPFM.WS_SPFMSoap.avisoFMAsync
            Return MyBase.Channel.avisoFMAsync(iCodPersonaResponsable, sNombrePersona, iTipoAviso, iGrupo)
        End Function
        
        Public Function avisoSPFMAsync(ByVal iCodPersonaResponsable As Integer, ByVal sNombrePersona As String, ByVal iTipoAviso As Integer, ByVal iGrupo As Integer) As System.Threading.Tasks.Task Implements WS_SPFM.WS_SPFMSoap.avisoSPFMAsync
            Return MyBase.Channel.avisoSPFMAsync(iCodPersonaResponsable, sNombrePersona, iTipoAviso, iGrupo)
        End Function
        
        Public Overridable Function OpenAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndOpen)
        End Function
        
        Public Overridable Function CloseAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndClose)
        End Function
        
        Private Shared Function GetBindingForEndpoint(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.Channels.Binding
            If (endpointConfiguration = EndpointConfiguration.WS_SPFMSoap) Then
                Dim result As System.ServiceModel.BasicHttpBinding = New System.ServiceModel.BasicHttpBinding()
                result.MaxBufferSize = Integer.MaxValue
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max
                result.MaxReceivedMessageSize = Integer.MaxValue
                result.AllowCookies = true
                Return result
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetEndpointAddress(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.EndpointAddress
            If (endpointConfiguration = EndpointConfiguration.WS_SPFMSoap) Then
                Return New System.ServiceModel.EndpointAddress("http://213.0.25.236:94/ws_spfm/ws_spfm.asmx")
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetDefaultBinding() As System.ServiceModel.Channels.Binding
            Return WS_SPFMSoapClient.GetBindingForEndpoint(EndpointConfiguration.WS_SPFMSoap)
        End Function
        
        Private Shared Function GetDefaultEndpointAddress() As System.ServiceModel.EndpointAddress
            Return WS_SPFMSoapClient.GetEndpointAddress(EndpointConfiguration.WS_SPFMSoap)
        End Function
        
        Public Enum EndpointConfiguration
            
            WS_SPFMSoap
        End Enum
    End Class
    
    <System.Xml.Serialization.XmlSchemaProviderAttribute(Nothing, IsAny:=true),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.ServiceReference.Platforms", "14.0.0.0")>  _
    Partial Public Class ArrayOfXElement
        Inherits Object
        Implements System.Xml.Serialization.IXmlSerializable
        
        Private nodesList As System.Collections.Generic.List(Of System.Xml.Linq.XElement) = New System.Collections.Generic.List(Of System.Xml.Linq.XElement)()
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Overridable ReadOnly Property Nodes() As System.Collections.Generic.List(Of System.Xml.Linq.XElement)
            Get
                Return Me.nodesList
            End Get
        End Property
        
        Public Overridable Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema
            Throw New System.NotImplementedException()
        End Function
        
        Public Overridable Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml
            Dim e As System.Collections.Generic.IEnumerator(Of System.Xml.Linq.XElement) = nodesList.GetEnumerator

            Do While e.MoveNext
                CType(e.Current,System.Xml.Serialization.IXmlSerializable).WriteXml(writer)

            Loop
        End Sub
        
        Public Overridable Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml

            Do While (reader.NodeType <> System.Xml.XmlNodeType.EndElement)
                If (reader.NodeType = System.Xml.XmlNodeType.Element) Then
                    Dim elem As System.Xml.Linq.XElement = New System.Xml.Linq.XElement("default")
                    CType(elem,System.Xml.Serialization.IXmlSerializable).ReadXml(reader)
                    Nodes.Add(elem)
                Else
                    reader.Skip
                End If

            Loop
        End Sub
    End Class
End Namespace
