'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


'
'This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
'
Namespace WS_SMARTPHONE
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WS_SMARTPHONE.SmartphoneSoap")>  _
    Public Interface SmartphoneSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Delegaciones", ReplyAction:="*")>  _
        Function DelegacionesAsync(ByVal request As WS_SMARTPHONE.DelegacionesRequest) As System.Threading.Tasks.Task(Of WS_SMARTPHONE.DelegacionesResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Consejos", ReplyAction:="*")>  _
        Function ConsejosAsync(ByVal request As WS_SMARTPHONE.ConsejosRequest) As System.Threading.Tasks.Task(Of WS_SMARTPHONE.ConsejosResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Informacion", ReplyAction:="*")>  _
        Function InformacionAsync(ByVal request As WS_SMARTPHONE.InformacionRequest) As System.Threading.Tasks.Task(Of WS_SMARTPHONE.InformacionResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DelegacionesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Delegaciones", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_SMARTPHONE.DelegacionesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_SMARTPHONE.DelegacionesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class DelegacionesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class DelegacionesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DelegacionesResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_SMARTPHONE.DelegacionesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_SMARTPHONE.DelegacionesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DelegacionesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public DelegacionesResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal DelegacionesResult As String)
            MyBase.New
            Me.DelegacionesResult = DelegacionesResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsejosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Consejos", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_SMARTPHONE.ConsejosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_SMARTPHONE.ConsejosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class ConsejosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsejosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsejosResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_SMARTPHONE.ConsejosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_SMARTPHONE.ConsejosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ConsejosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsejosResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsejosResult As String)
            MyBase.New
            Me.ConsejosResult = ConsejosResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class InformacionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Informacion", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_SMARTPHONE.InformacionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_SMARTPHONE.InformacionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class InformacionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class InformacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="InformacionResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WS_SMARTPHONE.InformacionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WS_SMARTPHONE.InformacionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InformacionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public InformacionResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal InformacionResult As String)
            MyBase.New
            Me.InformacionResult = InformacionResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SmartphoneSoapChannel
        Inherits WS_SMARTPHONE.SmartphoneSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SmartphoneSoapClient
        Inherits System.ServiceModel.ClientBase(Of WS_SMARTPHONE.SmartphoneSoap)
        Implements WS_SMARTPHONE.SmartphoneSoap
        
        ''' <summary>
        ''' Implement this partial method to configure the service endpoint.
        ''' </summary>
        ''' <param name="serviceEndpoint">The endpoint to configure</param>
        ''' <param name="clientCredentials">The client credentials</param>
        Partial Private Shared Sub ConfigureEndpoint(ByVal serviceEndpoint As System.ServiceModel.Description.ServiceEndpoint, ByVal clientCredentials As System.ServiceModel.Description.ClientCredentials)
        End Sub
        
        Public Sub New()
            MyBase.New(SmartphoneSoapClient.GetDefaultBinding, SmartphoneSoapClient.GetDefaultEndpointAddress)
            Me.Endpoint.Name = EndpointConfiguration.SmartphoneSoap.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration)
            MyBase.New(SmartphoneSoapClient.GetBindingForEndpoint(endpointConfiguration), SmartphoneSoapClient.GetEndpointAddress(endpointConfiguration))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As String)
            MyBase.New(SmartphoneSoapClient.GetBindingForEndpoint(endpointConfiguration), New System.ServiceModel.EndpointAddress(remoteAddress))
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal endpointConfiguration As EndpointConfiguration, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(SmartphoneSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
            Me.Endpoint.Name = endpointConfiguration.ToString
            ConfigureEndpoint(Me.Endpoint, Me.ClientCredentials)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_SMARTPHONE_SmartphoneSoap_DelegacionesAsync(ByVal request As WS_SMARTPHONE.DelegacionesRequest) As System.Threading.Tasks.Task(Of WS_SMARTPHONE.DelegacionesResponse) Implements WS_SMARTPHONE.SmartphoneSoap.DelegacionesAsync
            Return MyBase.Channel.DelegacionesAsync(request)
        End Function
        
        Public Function DelegacionesAsync() As System.Threading.Tasks.Task(Of WS_SMARTPHONE.DelegacionesResponse)
            Dim inValue As WS_SMARTPHONE.DelegacionesRequest = New WS_SMARTPHONE.DelegacionesRequest()
            inValue.Body = New WS_SMARTPHONE.DelegacionesRequestBody()
            Return CType(Me,WS_SMARTPHONE.SmartphoneSoap).DelegacionesAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_SMARTPHONE_SmartphoneSoap_ConsejosAsync(ByVal request As WS_SMARTPHONE.ConsejosRequest) As System.Threading.Tasks.Task(Of WS_SMARTPHONE.ConsejosResponse) Implements WS_SMARTPHONE.SmartphoneSoap.ConsejosAsync
            Return MyBase.Channel.ConsejosAsync(request)
        End Function
        
        Public Function ConsejosAsync() As System.Threading.Tasks.Task(Of WS_SMARTPHONE.ConsejosResponse)
            Dim inValue As WS_SMARTPHONE.ConsejosRequest = New WS_SMARTPHONE.ConsejosRequest()
            inValue.Body = New WS_SMARTPHONE.ConsejosRequestBody()
            Return CType(Me,WS_SMARTPHONE.SmartphoneSoap).ConsejosAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WS_SMARTPHONE_SmartphoneSoap_InformacionAsync(ByVal request As WS_SMARTPHONE.InformacionRequest) As System.Threading.Tasks.Task(Of WS_SMARTPHONE.InformacionResponse) Implements WS_SMARTPHONE.SmartphoneSoap.InformacionAsync
            Return MyBase.Channel.InformacionAsync(request)
        End Function
        
        Public Function InformacionAsync() As System.Threading.Tasks.Task(Of WS_SMARTPHONE.InformacionResponse)
            Dim inValue As WS_SMARTPHONE.InformacionRequest = New WS_SMARTPHONE.InformacionRequest()
            inValue.Body = New WS_SMARTPHONE.InformacionRequestBody()
            Return CType(Me,WS_SMARTPHONE.SmartphoneSoap).InformacionAsync(inValue)
        End Function
        
        Public Overridable Function OpenAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndOpen)
        End Function
        
        Public Overridable Function CloseAsync() As System.Threading.Tasks.Task
            Return System.Threading.Tasks.Task.Factory.FromAsync(CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(Nothing, Nothing), AddressOf CType(Me,System.ServiceModel.ICommunicationObject).EndClose)
        End Function
        
        Private Shared Function GetBindingForEndpoint(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.Channels.Binding
            If (endpointConfiguration = EndpointConfiguration.SmartphoneSoap) Then
                Dim result As System.ServiceModel.BasicHttpBinding = New System.ServiceModel.BasicHttpBinding()
                result.MaxBufferSize = Integer.MaxValue
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max
                result.MaxReceivedMessageSize = Integer.MaxValue
                result.AllowCookies = true
                Return result
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetEndpointAddress(ByVal endpointConfiguration As EndpointConfiguration) As System.ServiceModel.EndpointAddress
            If (endpointConfiguration = EndpointConfiguration.SmartphoneSoap) Then
                Return New System.ServiceModel.EndpointAddress("http://www.fraternidad-prevencion.com/WebService/Smartphone.asmx")
            End If
            Throw New System.InvalidOperationException(String.Format("Could not find endpoint with name '{0}'.", endpointConfiguration))
        End Function
        
        Private Shared Function GetDefaultBinding() As System.ServiceModel.Channels.Binding
            Return SmartphoneSoapClient.GetBindingForEndpoint(EndpointConfiguration.SmartphoneSoap)
        End Function
        
        Private Shared Function GetDefaultEndpointAddress() As System.ServiceModel.EndpointAddress
            Return SmartphoneSoapClient.GetEndpointAddress(EndpointConfiguration.SmartphoneSoap)
        End Function
        
        Public Enum EndpointConfiguration
            
            SmartphoneSoap
        End Enum
    End Class
End Namespace
